[local]
localhost

[mongodb]
mongodb.daws90s.fun

[redis]
redis.daws90s.fun

[mysql]
mysql.daws90s.fun

[rabbitmq]
rabbitmq.daws90s.fun

[catalogue]
catalogue.daws90s.fun

[user]
user.daws90s.fun

[cart]
cart.daws90s.fun

[shipping]
shipping.daws90s.fun

[payment]
payment.daws90s.fun

[frontend]
frontend.daws90s.fun